### ISSUE TITLE
jokerhere - 04b30fb4-647a-43d7-985e-3ad1b2810917- ADVANCED

### ISSUE THREAD

**Issue by jokerhere** [berbb/PAIO#197]

**Comment by jokerhere** [comment]
I bought the basic plan by mistake too, please make the payment reversal? 

 036c0ae4-c7e3-4c5c-8d3e-68d5ff96f490

**Comment by berbb** [comment]
Added and refunded the $1.

**Comment by jokerhere** [comment]
Where do I download the addons?

**Comment by berbb** [comment]
https://github.com/berbb/PAIO/wiki/Main-Installation-Guide
