### ISSUE TITLE
My EB username  meifualang  Order Transaction ID b1250a93-173e-44c3-a9ae-dd5e35804791  The Plan Type is i can not find that but i think it is Full access - Access to all dual-ports - Access to all Utilities (Evade, Activators, Trackers)I paid three doalls a month

### ISSUE THREAD

**Issue by meifualang** [berbb/PAIO#24]
Hello i just want to know i only paid three dollars a moth and i get everychamp like old L= or the old port Aio right ? or i need to paid more please let me know i do not mind to pay i just want to use .Long time to wait for port aio update wait for ur reply thanks

**Comment by meifualang** [comment]
And when u done Can u just give me email back my email is daodaowenni064@gmail.com thanks

**Comment by berbb** [comment]
done!

**Comment by meifualang** [comment]
Hello sir whats up


2017-06-28 15:34 GMT-06:00 Berb <notifications@github.com>:

**Comment by meifualang** [comment]
seems not done i Still can not use that

**Comment by berbb** [comment]
Did you spell your Username correctly?

**Comment by meifualang** [comment]
Yes i give u again  meifualang  Here is user name maybe sir i need to buy
some champin script ?i use olaf as custom game it is said olaf not free but
i m sure i already paid 3 Usd


2017-06-28 16:47 GMT-06:00 Berb <notifications@github.com>:

**Comment by berbb** [comment]
I already auth'd you, are you sure?

**Comment by meifualang** [comment]
I can use now thank u sir

发自我的 iPhone

**Comment by meifualang** [comment]
Sorry sir now i can not use that it is said let me update i tried but still not working

发自我的 iPhone

**Comment by berbb** [comment]
Install PAIO the same way you did it the first time. I pushed an update.

**Comment by meifualang** [comment]
Ok  sure

2017-06-28 17:43 GMT-06:00 Berb <notifications@github.com>:
