### ISSUE TITLE
Jucemar5 / 1a0b52b8-1aa2-4a46-99ef-8c75a28f530a / Advanced Plan ($3) - 1 Month

### ISSUE THREAD

**Issue by Jucemar5** [berbb/PAIO#266]
Eu não falo em inglês , meu nome de usuário no EB é Jucemar5, eu sou membro free.
Comprei o advanced plan , ID de fatura: 1a0b52b8-1aa2-4a46-99ef-8c75a28f530a

Language: Português

**Comment by berbb** [comment]
added
