### ISSUE TITLE
Yaugernet b4be43fd-dddc-47f5-99d4-c469db697902 advanced

### ISSUE THREAD

**Issue by yaugernet** [berbb/PAIO#286]
Product Details

You have recently purchased from Selly. The details for said purchase can be found below.

Product: PortAIO - Advanced Plan - 1 Month

Quantity: 1

Order ID: b4be43fd-dddc-47f5-99d4-c469db697902

Seller's Note: Thanks for buying the advanced plan! You will be pushed within 12 hours.

thanks bro!!!

**Comment by berbb** [comment]
added
