### ISSUE TITLE
EB Username : kingammarre / order ID : 17212ab7-7d79-4023-b293-bc3cf22458c8  / Advanced Plan ($3)

### ISSUE THREAD

**Issue by kingammarre** [berbb/PAIO#31]
HI
EB Username : kingammarre

order ID : 17212ab7-7d79-4023-b293-bc3cf22458c8

I paid for Advanced Plan ($3)

Email Paypal : mst5sr@outlook.sa

https://image.prntscr.com/image/9USGyxagTLaoeENanf6NWg.png

**Comment by berbb** [comment]
Added.
