### ISSUE TITLE
tampla48

### ISSUE THREAD

**Issue by tampla48** [berbb/PAIO#324]
ID : 1534c880-9ee1-4d12-b851-fc7c58d8f9b8
Advanced plan 1 month !

**Comment by berbb** [comment]
I can't find a order id with 1534c880-9ee1-4d12-b851-fc7c58d8f9b8.

**Comment by tampla48** [comment]
hm i can send you the message completly

**Comment by tampla48** [comment]
ID de transaction : 1534c880-9ee1-4d12-b851-fc7c58d8f9b8

Type de transaction : retrait de fonds

Montant : 0.00126967 BTC

Type de destination : adresse Bitcoin

Destination : 1pEwg4fQUPkJqNExihVXmEZmj776YjoAz

Code d'autorisation : d220df092b0a75d8fffaec4c6363a3d8

**Comment by tampla48** [comment]
i send you man :)  the proof is here

**Comment by tampla48** [comment]
08ef305e544637493533d7346a8d8a84cf417289
i don't know if it's the order code ,

**Comment by berbb** [comment]
Added
