### ISSUE TITLE
Product Details

### ISSUE THREAD

**Issue by kwonosu1** [berbb/PAIO#333]
Product Details
 
You have recently purchased from Selly. The details for said purchase can be found below.
Product: PortAIO - Advanced Plan - 1 Month
Quantity: 1
Order ID: b2a96932-19bb-42bd-b1b8-f231664d3230
Seller's Note: Thanks for buying the advanced plan! You will be pushed within 12 hours.
Download Link: 
https://selly.gg/downloads/7e78aa803c66129a6333cc557db876f9c88dc785cae4850d581f787dc19c4784e318b6d7d8d84472721f17c331aa0e238900f5232d0c4a67afa00f22c3c363b5
If you would like to leave the seller feedback, please follow the link. It can be used later to edit the feedback.

elobuddy.net : kwonosu1

**Comment by berbb** [comment]
added
