### ISSUE TITLE
EB: RadhG     Order ID: 01969e39-ee70-4514-8b6a-6bfbbb2b2347 [advanced]

### ISSUE THREAD

**Issue by bimaradh** [berbb/PAIO#36]
Product Details

You have recently purchased from Selly. The details for said purchase can be found below.

Product: PortAIO - Advanced Plan - 1 Month

Quantity: 1

Order ID: 01969e39-ee70-4514-8b6a-6bfbbb2b2347

**Comment by berbb** [comment]
Pushed.
