### ISSUE TITLE
jrinked / c16a3e04-c385-4dae-9576-130bd04b449d / Advanced

### ISSUE THREAD

**Issue by juniorinked** [berbb/PAIO#43]
kayn is a future hahahaha

**Comment by berbb** [comment]
done!

**Comment by juniorinked** [comment]
I can not use AIO! Not the injected inside the game!

2017-06-28 23:08 GMT-03:00 Berb <notifications@github.com>:

**Comment by berbb** [comment]
Did you give me the correct username.

**Comment by juniorinked** [comment]
EB:  jrinked

2017-06-30 0:06 GMT-03:00 Berb <notifications@github.com>:

**Comment by berbb** [comment]
You should be authed that's exactly what I put.
