### ISSUE TITLE
gohopak | e161c25e-9a27-4a87-991b- 522b03a23372 | Advanced Plan

### ISSUE THREAD

**Issue by gohopak** [berbb/PAIO#97]
Hi

i want "all utility, champ(cassi, olaf, etc)

plz~

**Comment by berbb** [comment]
I can't find your transaction ID, are you sure that's the right one?

**Comment by gohopak** [comment]
Transaction Id : 10191306FS0337055
Order Id :  e161c25e-9a27-4a87-991b- 522b03a23372
ELO Id : gohopak
thx ~ berbb

**Comment by berbb** [comment]
got it. added
